name: overlay_model
description: easier way and advanced control on flutter overlay insertion, update, removal in State.
version: 0.0.2
repository: https://github.com/nomagicisreal/overlay_model

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0
